services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-idp-postgres
    environment:
      POSTGRES_DB: mini_idp
      POSTGRES_USER: mini_idp_user
      POSTGRES_PASSWORD: mini_idp_password
    ports:
      - "5433:5432"
    volumes:
      - mini_idp_pgdata:/var/lib/postgresql/data

volumes:
  mini_idp_pgdata: