server:
  port: 9000
  forward-headers-strategy: framework

spring:
  application:
    name: idp-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/mini_idp}
    username: ${DB_USER:mini_idp_user}
    password: ${DB_PASSWORD:mini_idp_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}

app:
  security:
    issuer: ${APP_ISSUER:http://localhost:9000}
    encryption-secret: ${APP_ENCRYPTION_SECRET:dev-only-change-this-secret-before-deploying-123456}

  jwt:
    audience: ${APP_JWT_AUDIENCE:client-app}
    access-token-minutes: ${APP_JWT_ACCESS_TOKEN_MINUTES:15}

  client:
    base-url: ${CLIENT_BASE_URL:http://localhost:8080}

  oauth:
    default-client:
      client-id: ${APP_OAUTH_CLIENT_ID:client-app}
      client-secret: ${APP_OAUTH_CLIENT_SECRET:client-secret-123}
      name: ${APP_OAUTH_CLIENT_NAME:Client App}
      redirect-uri: ${APP_OAUTH_REDIRECT_URI:http://localhost:8080/callback}
      allowed-scopes: ${APP_OAUTH_ALLOWED_SCOPES:openid profile email}

  mail:
    from: ${APP_MAIL_FROM:no-reply@mini-idp.local}

  totp:
    issuer: ${APP_TOTP_ISSUER:Mini IdP}